#!/usr/bin/env python3

Author: Malena Tomlin
Course: Ops 301 Challenge 10 - Super Troopers
Date:   12/2023

import os

# Variable Declarations:

# Create a new movie file named "SuperTroopers.txt"
movie_path = "SuperTroopers.txt"

# Main

# Open movie file with permissions then assign it to the "movie" variable:
with open(movie_path, "w") as movie:
  # Write three lines related to "Super Troopers" to the movie file:
  movie.write("Super Troopers\n")
  movie.write("A comedy about five Vermont state troopers who get into various shenanigans.\n")
  movie.write("Do I look like a cat to you, boy? Am I jumpin' around all nimbly bimbly from tree to tree?\n")

# Read the contents in movie file:
with open(movie_path, "r") as movie:
  # Read the first line of the file, then print:
  first_line = movie.readline()
  print("First line:", first_line.strip())

# Close movie file:
movie.close()

# Remove movie file:
os.remove(movie_path)

# End
